### ISSUE TITLE
Support for multi-region ECR pushes

### ISSUE THREAD

**Issue by msb00003** [drone-plugins/drone-ecr#30]
Currently it seems I can only push to one region at a time due to the credentials setup.

I would like support for being able to build it once, then auth+push to each region, currently I have the step replicated per region, which takes a fair while. [the cache of each layer made this comparatively quick, so now I am more requesting a nicer syntax]

For example:

```
publish:
  ecr:
    repo: repo/repo
    tag:
      - latest
      - 1.0.$$BUILD_NUMBER
    region:
      - eu-west-1
      - eu-central-1
      - ap-northeast-1
      - ap-southeast-1
    storage_driver: overlay
    create_repository: True
    when:
        branch: master
```

To work
