### ISSUE TITLE
Possible to Override Default Entrypoint?

### ISSUE THREAD

**Issue by darahayes** [drone-plugins/drone-ecr#33]
Hi there,

I have a bit of an edge case where I want to use this plugin but I want to override the default entrypoint. I want to be able to run my own script that does the docker push stuff. The reason is so I can read in additional secrets and have some flexibility. Example of my `.drone.yml` file below:

```
publish:
    image: plugins/ecr
    commands:
      - ./scripts/deploy/docker-push.sh staging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

When I tried this I got the following:

```
ERROR: Custom entrypoint disabled for the plugins/ecr:latest plugin
```
I'd like to do it with this image because it is conveniently built on top of the `plugins/docker` image and it also already has the `awscli`module installed.

Is it possible to get around this? Or should I just build my own image? Thanks
