### ISSUE TITLE
Use drone secrets in build_args

### ISSUE THREAD

**Issue by Dineshs91** [drone-plugins/drone-ecr#37]
How to use drone secrets in build_args ?

I've tried to access it in the following ways, but none of them works.

```
secrets: [ server_name ]
build_args:
      - "SERVER_NAME=${SERVER_NAME}"
```

```
secrets: [ server_name ]
build_args:
      - SERVER_NAME=${SERVER_NAME}
```

```
secrets: [ server_name ]
build_args:
      - SERVER_NAME=$SERVER_NAME
```

**Environment:**
```
drone: 0.7
```

**Comment by Dineshs91** [comment]
The hack proposed by @bradrydzewski works.

```
secrets:
  - source: docker_build_args
    target: plugin_build_args
```

Have the secret with name: `docker_build_args` and value: `foo=bar,baz=boo`

**Comment by vishal24tuniki** [comment]
@Dineshs91 @bradrydzewski 
can you please give an example with both .yml and secret key, value ?

**Comment by bradrydzewski** [comment]
Dinesh provides an example in https://github.com/drone-plugins/drone-ecr/issues/37#issuecomment-319114327

**Comment by vishal24tuniki** [comment]
It is not clear. Please clarify if what i think is correct or not as per my #47 

Create a drone secret with key as `my_build_args` and value as `GITHUB_OAUTH_TOKEN=xxx`

```
publish:
    image: plugins/ecr
    ........
    ........
    secrets:
        - ecr_access_key
        - ecr_secret_key
        - ecr_region
        - source: my_build_args
          target: plugin_build_args
```

**Comment by vishal24tuniki** [comment]
@bradrydzewski , can you please comment if my understanding is correct?

**Comment by vishal24tuniki** [comment]
This worked :+1: 
```
publish:
    image: plugins/ecr
    ........
    ........
    secrets:
      - source: ecr_access_key
        target: ecr_access_key
      - source: ecr_secret_key
        target: ecr_secret_key
      - source: ecr_region
        target: ecr_region
      - source: my_build_args
        target: plugin_build_args
```

**Comment by rakhmanov** [comment]
Can this limitation be explained? This is way more hackier than supposed to.

**Comment by bradrydzewski** [comment]
If the goal is to pass secrets as build args, there is a better way:

```
pipeline:
  publish:
    image: plugins/docker
    secrets: [ FOOBAR ]
    build_args_from_env: [ FOOBAR ]
```

Secrets are passed to the plugin as environment variables. If you want to load build arguments from environment variables, you provide `build_args_from_env` with a list of environment variables that should be set as build args.
