### ISSUE TITLE
Error parsing reference: ":latest" is not a valid repository/tag

### ISSUE THREAD

**Issue by amaziagur** [drone-plugins/drone-ecr#45]
Hi,

im keep getting the following parsing error regadles to the tag configuration i put.

here is my .drone.yml:

```
pipeline:
  publish:
    image: plugins/ecr
    ecr:
      access_key: my_key
      secret_key: my_secret
      region: eu-central-1
      repo: my_repo/pusher
      registry: my_registry
      file: Dockerfile
      tags:
        - latest
        - 1.0.1
        - 1.0
    when:
          branch: master
```
iv'e tried variations of tag decelerations (arrays or using 'tag' as the key).

and nothing works.

im running drone in docker-compose and here is the following configuration:

```
drone 0.7.3
plugins/ecr latest

--my docker version

Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
any ideas?

**Comment by tboerger** [comment]
Your yaml got a wrong format:

```
pipeline:
  publish:
    image: plugins/ecr
    access_key: my_key
    secret_key: my_secret
    region: eu-central-1
    repo: my_repo/pusher
    registry: my_registry
    file: Dockerfile
    tags:
      - latest
      - 1.0.1
      - 1.0
    when:
      branch: master
```

You should take a look at https://docs.drone.io
