### ISSUE TITLE
name unkown

### ISSUE THREAD

**Issue by Michael-Reich** [drone-plugins/drone-ecr#52]
Hello everyone,

I tested drone and had a problem with this pipeline, I got an error name unknown:

- aws key has full-access
- aws key has permission on ecr
- ecr name is the same

```
pipeline:
  ecr:
    image: plugins/ecr
    access_key: xxx
    secret_key: xxx
    repo: 347501067673.dkr.ecr.eu-central-1.amazonaws.com/sample-web-app
    registry: 347501067673.dkr.ecr.eu-central-1.amazonaws.com
    # secrets: [ ecr_access_key, ecr_secret_key ]
    tags:
      - 1.0
    dockerfile: Dockerfile
  rancher:
    image: peloton/drone-rancher
    url: xxx
    access_key: xxx
    secret_key: xxx
    service: webapp/sample-web-app
    docker_image: 347501067673.dkr.ecr.eu-central-1.amazonaws.com/sample-web-app:latest
    start_first: true
    confirm: true
    timeout: 180
```

```
+ /usr/local/bin/dockerd -g /var/lib/docker
+ /usr/local/bin/docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:05:38 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
+ /usr/local/bin/docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Alpine Linux v3.7 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.2MiB
Name: 21b234108c5e
ID: 3TKM:3EDL:SURG:V3J7:B64D:QI5R:QI5E:N3WP:K7QJ:B2JO:FEWC:6FHZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: drone
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

+ /usr/local/bin/docker build --rm=true -f Dockerfile -t 46191726d16130dd7dd67fcb9ca2966494002e70 . --pull=true --build-arg no_proxy=drone --build-arg NO_PROXY=drone --label org.label-schema.build-date=2018-03-12T20:49:13Z --label org.label-schema.vcs-ref=46191726d16130dd7dd67fcb9ca2966494002e70 --label org.label-schema.vcs-url=https://bitbucket.org/trefox/sampleapp.git
Sending build context to Docker daemon  109.1kB

Step 1/6 : FROM nginx
latest: Pulling from library/nginx
8176e34d5d92: Pulling fs layer
5b19c1bdd74b: Pulling fs layer
4e9f6296fa34: Pulling fs layer
4e9f6296fa34: Verifying Checksum
4e9f6296fa34: Download complete
5b19c1bdd74b: Verifying Checksum
5b19c1bdd74b: Download complete
8176e34d5d92: Verifying Checksum
8176e34d5d92: Download complete
8176e34d5d92: Pull complete
5b19c1bdd74b: Pull complete
4e9f6296fa34: Pull complete
Digest: sha256:4771d09578c7c6a65299e110b3ee1c0a2592f5ea2618d23e4ffe7a4cab1ce5de
Status: Downloaded newer image for nginx:latest
 ---> e548f1a579cf
Step 2/6 : ENV AUTHOR=Docker
 ---> Running in fea4789ac05a
Removing intermediate container fea4789ac05a
 ---> 2530cf9d1812
Step 3/6 : WORKDIR /usr/share/nginx/html
Removing intermediate container 7adb73c8f317
 ---> 2e90d4d52de6
Step 4/6 : COPY Hello_docker.html /usr/share/nginx/html
 ---> 4796748e8009
Step 5/6 : CMD cd /usr/share/nginx/html && sed -e s/Docker/"$AUTHOR"/ Hello_docker.html > index.html ; nginx -g 'daemon off;'
 ---> Running in 47cadd9137f3
Removing intermediate container 47cadd9137f3
 ---> c0008573921d
Step 6/6 : LABEL "org.label-schema.build-date"='2018-03-12T20:49:13Z' "org.label-schema.vcs-ref"='46191726d16130dd7dd67fcb9ca2966494002e70' "org.label-schema.vcs-url"='https://bitbucket.org/trefox/sampleapp.git'
 ---> Running in fef26d5362e1
Removing intermediate container fef26d5362e1
 ---> 049c25c35c07
Successfully built 049c25c35c07
Successfully tagged 46191726d16130dd7dd67fcb9ca2966494002e70:latest
+ /usr/local/bin/docker tag 46191726d16130dd7dd67fcb9ca2966494002e70 347501067673.dkr.ecr.us-east-1.amazonaws.com/347501067673.dkr.ecr.eu-central-1.amazonaws.com/sample-web-app:1
+ /usr/local/bin/docker push 347501067673.dkr.ecr.us-east-1.amazonaws.com/347501067673.dkr.ecr.eu-central-1.amazonaws.com/sample-web-app:1
The push refers to repository [347501067673.dkr.ecr.us-east-1.amazonaws.com/347501067673.dkr.ecr.eu-central-1.amazonaws.com/sample-web-app]
a615eb000043: Preparing
e89b70d28795: Preparing
832a3ae4ac84: Preparing
014cf8bfcb2d: Preparing
name unknown: The repository with name '347501067673.dkr.ecr.eu-central-1.amazonaws.com/sample-web-app' does not exist in the registry with id '347501067673'
time="2018-03-12T20:49:27Z" level=fatal msg="exit status 1"
```
